### ISSUE TITLE
Does it still need us to build qtbase and  qtdeclarative from the dev branch? 

### ISSUE THREAD

**Issue by shujaatak** [KDAB/DeclarativeWidgets#24]
I wonder whether DeclarativeWidgets still need us to build **qtbase** and **qtdeclarative** from the dev branch.

**Comment by shujaatak** [comment]
The changed DeclarativeWidgets required are already committed:
https://codereview.qt-project.org/c/qt/qtdeclarative/+/73592

**Comment by jcelerier** [comment]
Hello, 
I've just tested - it seems to work fine with a stock Qt 5.14 for instance.

**Comment by shujaatak** [comment]
> Hello,
> I've just tested - it seems to work fine with a stock Qt 5.14 for instance.

This means the Readme file should be updated!

**Comment by shujaatak** [comment]
> Hello,
> I've just tested - it seems to work fine with a stock Qt 5.14 for instance.

Running bookstore example crashes with the following messages, other examples run fine:
```
authorTable.rowCount= 4
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
QQmlComponent: Component is not ready
Failed to create widget from QML
14:49:09: The program has unexpectedly finished.
14:49:09: The process was ended forcefully.
```
An I missing something?

**Comment by shujaatak** [comment]
I noticed that Admin.qml and Staff.qml run fine but when I selected Developer.qml then the application crashes.

**Comment by 0x6e** [comment]
> That change on which DeclarativeWidgets used to depend has already committed:
> https://codereview.qt-project.org/c/qt/qtdeclarative/+/73592

It looks like you should be able to use any version of Qt >= 5.11

**Comment by 0x6e** [comment]
> I noticed that Admin.qml and Staff.qml run fine but when I selected Developer.qml then the application crashes.

I haven't managed to reproduce this with the debugger yet. I haven't figured out steps to reproduce this reliably. Does it occur for you every time?
