### ISSUE TITLE
Example  crash

### ISSUE THREAD

**Issue by caeit** [KDAB/DeclarativeWidgets#27]
The example crash on qt5.12.4 on msvc2017 x64. The output is as following:

authorTable.rowCount= 4
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
QQmlComponent: Component is not ready
Failed to create widget from QML

After I call QCoreApplication::setAttribute(Qt::AA_ShareOpenGLContexts) as the first line of the the bookstore/main.cpp/main function, the output about qwebengine disappear, but it still crash. Need help. Thanks.

**Comment by 0x6e** [comment]
Hi @caeit can you pull and try again?

Please also make sure you have performed the install step outlined in the Readme.md.

**Comment by caeit** [comment]
It's interesting:)
