### ISSUE TITLE
Can't build on Windows...

### ISSUE THREAD

**Issue by fluffyluke707** [KDAB/DeclarativeWidgets#5]
I am trying to build the library with MSVC 2017 64bit in Qt but it won't build.
Here are the errors 
`error: LNK1104: cannot open file declarativewidgets.lib`
`LINK : fatal error LNK1146: no argument specified with option '/LIBPATH:'`

**Comment by fluffyluke707** [comment]
I tried to compiled the lib as static lib in Qt but it still doesn't work

**Comment by iamsergio** [comment]
If you cd into lib/ and try to build that, does it work ?

**Comment by 0x6e** [comment]
DeclarativeWidgets also depends upon this change, otherwise it will crash at runtime: https://codereview.qt-project.org/#/c/73592/

I will fix the build and update the README.md to reflect this requirement.

**Comment by fluffyluke707** [comment]
it works when I CD into the lib, but it doesn't output a .lib only outputs a dll

**Comment by fluffyluke707** [comment]
Ok, I tried to build declarativewidgets.pro after you updated, and I am only getting these errors now.
``

**Comment by fluffyluke707** [comment]
Ok, what you did fixed most of the errors but the problem is it says it cannot find declarativewidgets.lib. For some reason Qt isn't outputting a .lib and .dll it's only outputting a .dll and then the error becomes cannot find declarativewidget.dll. I tried adding the option `CONFIG += staticlib` in the library .pro file and while it outputs a .dll and .lib I end up getting a bunch of errors such as these - `http://imgur.com/a/FQfKx`

**Comment by shujaatak** [comment]
> DeclarativeWidgets also depends upon this change, otherwise it will crash at runtime: https://codereview.qt-project.org/#/c/73592/
> 
> I will fix the build and update the README.md to reflect this requirement.

I think this change has already included in the Qt, see here: https://codereview.qt-project.org/c/qt/qtdeclarative/+/73592

**Comment by 0x6e** [comment]
DeclarativeWidgets is building fine on Windows. Please let us know if you are still having issues.
